services:
  app:
    build: ./app
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: ${MONGO_URI}
      GOOGLE_MAP_API_KEY: ${GOOGLE_MAP_API_KEY}
    volumes:
      - ./app/src:/app
      
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_URI: ${MONGO_URI}
      GOOGLE_MAP_API_KEY: ${GOOGLE_MAP_API_KEY}

volumes:
  mongo_data: {}