version: '3.8'

services:
  app:
    image: eth3r3ai/lastone:latest  # pull from DockerHub
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: ${MONGO_URI}
      GOOGLE_MAP_API_KEY: ${GOOGLE_MAP_API_KEY}
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_URI: ${MONGO_URI}
      GOOGLE_MAP_API_KEY: ${GOOGLE_MAP_API_KEY}
    restart: always

volumes:
  mongo_data: {}
