name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ./app
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up environment variables
      env:
        TEST_MONGO_URI: ${{ secrets.TEST_MONGO_URI }}
        MONGO_DBNAME: test
        FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
      run: |
        echo "TEST_MONGO_URI=mongodb://localhost:27017/test_geometric_journal_db" >> $GITHUB_ENV
        echo "MONGO_DBNAME=test" >> $GITHUB_ENV
        echo "FLASK_SECRET_KEY=test_secret_key" >> $GITHUB_ENV
    
    - name: Run tests
      run: |
        pytest -v
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

  build:
    needs: test-and-build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t your-app-name .
      
    - name: Run Docker container
      run: docker-compose up -d
      env:
        MONGO_DBNAME=final
        MONGO_URI=${{ secrets.MONGO_URI }}
        SECRET_KEY='12345'
        GOOGLE_MAP_API_KEY = ${{ secrets.GOOGLE_MAP_API_KEY }}
        FLASK_ENV: test
